### ISSUE TITLE
Drab dislike HTML comments when they appears inside a do..end eex block in a child file 

### ISSUE THREAD

**Issue by guidotripaldi** [grych/drab#111]
Sorry, I'm here again with something that appears as a little bug. It seems that in certain conditions Drab has problem in compiling `.drab` files when it encounter an HTML comment ( i.e. `<!--FOO-->` ) inside a `do` .. `end` block, exiting the compiler with the error:

```
    The following arguments were given to Drab.Live.EExEngine.ampered_tag?/1:

        # 1
        {:comment, "FOO"}
```

The following is an example where I was able to reproduce the problem I encountered in a much more complex code:

```elixir
# templates/page/home.html.eex

<%= render( MyApp.PageView, "_drab_test_child.html", data: [1,2,3]) %>

```

```elixir
# templates/page/_drab_test_child.html
<%= if @data do %>
    <!--FOO-->
	<div>
	</div>
<% end %>
```

```
15:25:40.345 [info]  Compiling Drab partial: lib/my_app_web/templates/page/_drab_test_child.html.drab (geydgnrsheydqmbu)

== Compilation error in file lib/my_app_web/views/page_view.ex ==
** (FunctionClauseError) no function clause matching in Drab.Live.EExEngine.ampered_tag?/1

    The following arguments were given to Drab.Live.EExEngine.ampered_tag?/1:

        # 1
        {:comment, "FOO"}

    Attempted function clauses (showing 2 out of 2):

        defp ampered_tag?({_, attributes, _})
        defp ampered_tag?(string) when is_binary(string)

    lib/drab/live/eex_engine.ex:347: Drab.Live.EExEngine.ampered_tag?/1
    (elixir) lib/enum.ex:2955: Enum.reject_list/2
    (elixir) lib/enum.ex:2958: Enum.reject_list/2
    lib/drab/live/eex_engine.ex:322: Drab.Live.EExEngine.assigns_and_parents_from_pattern/1
    lib/drab/live/eex_engine.ex:201: anonymous fn/2 in Drab.Live.EExEngine.handle_body/1
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/drab/live/eex_engine.ex:195: anonymous fn/3 in Drab.Live.EExEngine.handle_body/1
    (stdlib) lists.erl:1263: :lists.foldl/3
$
```

Instead, if the HTML comment is outside the `do` .. `end` block:
```elixir
# templates/page/_drab_test_child.html
<%= if @data do %>
<% end %>
<!--FOO-->
    <div>
    </div>
```
it compiles without any error.

--EDIT--
It seems that the problem arises when the HTML comment is the first thing inside the `do`..`end`  block, in fact this works:

```elixir
# templates/page/_drab_test_child.html
<%= if @data do %>
	<div>
           <!--FOO-->
	</div>
<% end %>
```

**Comment by grych** [comment]
Thanks a lot for reporting! This is a bug in a custom eex engine
