### ISSUE TITLE
Compilation error when accessing assigns inside a `case` block if followed by an eex block accessing assigns inside an HTML tag

### ISSUE THREAD

**Issue by guidotripaldi** [grych/drab#112]
I got a compilation error when a `case` block is followed by an eex block accessing an assigns, but only when the last is enclosed in an HTML tag, like in the following basic example

This code rises a compilation error:
```eex
# _my_partial.eex.drab

  <%= 
    title =
        case @user.status do
            "1" -> "Enabled"
            "0" -> "Disabled"
            _   -> "Undefined"
        end
    # do something with `title`
  %>	

<div>
  <%= 
    status = @user.status
    # do something with `status`
  %>
</div>
```

Error:
```
== Compilation error in file lib/my_app_web/views/test_view.ex ==
** (FunctionClauseError) no function clause matching in Macro.do_traverse_args/4

    The following arguments were given to Macro.do_traverse_args/4:

        # 1
        "1Enabled"

        # 2
        nil

        # 3
        #Function<18.28811459/2 in Macro.prewalk/2>

        # 4
        #Function<19.28811459/2 in Macro.prewalk/3>

    Attempted function clauses (showing 2 out of 2):

        defp do_traverse_args(args, acc, _pre, _post) when is_atom(args)
        defp do_traverse_args(args, acc, pre, post) when is_list(args)

    (elixir) lib/macro.ex:271: Macro.do_traverse_args/4
    (elixir) lib/macro.ex:243: Macro.do_traverse/4
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:263: Macro.do_traverse/4
    (elixir) lib/macro.ex:258: Macro.do_traverse/4
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:263: Macro.do_traverse/4
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
```

Instead, if the `case` block isn't followed by an HTML enclosing tag, or if both the exx blocks are inside the same HTML enclosing tag, it compile without errors

this code will compile without errors:
```eex
# _my_partial.eex.drab

  <%= 
    label =
        case @user.status do
            "0" -> "Disabled"
            "1" -> "Enabled"
            _   -> "Undefined"
        end
  %>	

  <%= 
    status = @user.status
  %>
```
also this code will compile without errors:
```eex
# _my_partial.eex.drab

<div>
  <%= 
    label =
        case @user.status do
            "0" -> "Disabled"
            "1" -> "Enabled"
            _   -> "Undefined"
        end
  %>	

  <%= 
    status = @user.status
  %>
</div>
```

It will compile without error also when `if` is used instead of `case`, followed by the eex block encolsed in the HTML tag:

```eex
# _my_partial.eex.drab

  <%= 
    label =
        if @user.status == "1" do
            "Enabled"
        else "Disabled"
        end
  %>	

<div>
  <%= 
    status = @user.status
  %>
</div>
```

**Comment by grych** [comment]
Hey, thanks for reporting! It is because in this case Drab must inject <span> at the beginning of the expression - the bug must be in this code part.
