### ISSUE TITLE
Unable to join the Drab Channel {reason: "join crashed"}

### ISSUE THREAD

**Issue by GusGA** [grych/drab#177]
Hi @grych I'm having this error

```
[error] an exception was raised:
    ** (KeyError) key :__commander not found in: %{}
        (drab) lib/drab.ex:655: Drab.get_commander/1
        (drab) lib/drab.ex:165: Drab.start_link/1
        (drab) lib/drab/channel.ex:11: Drab.Channel.join/3
        (phoenix) lib/phoenix/channel/server.ex:245: Phoenix.Channel.Server.init/1
        (stdlib) gen_server.erl:374: :gen_server.init_it/2
        (stdlib) gen_server.erl:342: :gen_server.init_it/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

I'm using phoenix 1.4 with webpack.

**Comment by grych** [comment]
Hi @GusGA, could  you please check the current master? I believe the issue is already fixed.

**Comment by GusGA** [comment]
Yeah, the master branch has the issue fixed.

Thank you very much.
