### ISSUE TITLE
Drab on heroku

### ISSUE THREAD

**Issue by peterfication** [grych/drab#46]
Hey there, I'm new to Elixir and Phoenix. When I saw this amazing library I had to check it out. [I've built a basic calculator](https://github.com/peterfication/calculator) to play around with the features of drab. My local version works fine :)

Then I wanted to deploy it to Heroku (https://drab-calculator.herokuapp.com/) but I get the following error and I can't figure out what's special on Heroku.

```
2017-08-20T12:43:27.938626+00:00 app[web.1]: ** (RuntimeError) Ampere "geydcobvga2do" can't be found in Drab Cache.
2017-08-20T12:43:27.938627+00:00 app[web.1]:     (drab) lib/drab/live.ex:371: anonymous fn/6 in Drab.Live.do_poke/5
2017-08-20T12:43:27.938628+00:00 app[web.1]:     (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
2017-08-20T12:43:27.938629+00:00 app[web.1]:     (drab) lib/drab/live.ex:309: Drab.Live.do_poke/5
2017-08-20T12:43:27.938630+00:00 app[web.1]:     (drab) lib/drab.ex:249: anonymous fn/6 in Drab.handle_event/6
```

Any help and hints appreciated :)

**Comment by grych** [comment]
It must be similar to #37 (:code.priv_dir())

**Comment by peterfication** [comment]
Ok my problem was that I didn't commit my `·/priv/hashes_expressions.drab.cache.prod` because I thought I shouldn't commit cache files. Now it works :)

Thanks @grych, the linked issue helped me to find this out.

**Comment by grych** [comment]
It was OK. You shouldn't commit it.
The file should be creating during the compilation on heroku. Re-opening the issue to investigate.
