### ISSUE TITLE
Drab doesn't work for umbrella projects

### ISSUE THREAD

**Issue by justincjohnson** [grych/drab#47]
I tried adding Drab 0.5.4 to a new Phoenix 1.3.0 project.  It works fine adding to a normal project but when I add to an umbrella project I get the following error when running `mix phx.server` from the top level of the umbrella project.

```
$ mix phx.new app --umbrella
#...
cd app_umbrella
# vim apps/app_web/mix.exs to add drab dep
$ mix ecto.create
#...
$ mix phx.server
[info] Application drab exited: exited in: Drab.Supervisor.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (Protocol.UndefinedError) protocol String.Chars not implemented for {:error, :bad_name}. This protocol is implemented for: Atom, BitString, Date, DateTime, Decimal, Ecto.Date, Ecto.DateTime, Ecto.Time, Float, Integer, List, NaiveDateTime, Postgrex.Copy, Postgrex.Query, Postgrex.Stream, Time, URI, Version, Version.Requirement
            (elixir) /private/tmp/elixir-20170801-32483-1rf8an1/elixir-1.5.1/lib/elixir/lib/string/chars.ex:3: String.Chars.impl_for!/1
            (elixir) /private/tmp/elixir-20170801-32483-1rf8an1/elixir-1.5.1/lib/elixir/lib/string/chars.ex:22: String.Chars.to_string/1
            (drab) lib/drab/live/cache.ex:60: Drab.Live.Cache.cache_file/0
            (drab) lib/drab/live/cache.ex:24: Drab.Live.Cache.start/0
            (drab) lib/drab/supervisor.ex:26: Drab.Supervisor.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
[info] Application phoenix_live_reload exited: :stopped
[info] Application file_system exited: :stopped
[info] Application phoenix_html exited: :stopped
[info] Application cowboy exited: :stopped
[info] Application cowlib exited: :stopped
[info] Application ranch exited: :stopped
** (Mix) Could not start application drab: exited in: Drab.Supervisor.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (Protocol.UndefinedError) protocol String.Chars not implemented for {:error, :bad_name}. This protocol is implemented for: Atom, BitString, Date, DateTime, Decimal, Ecto.Date, Ecto.DateTime, Ecto.Time, Float, Integer, List, NaiveDateTime, Postgrex.Copy, Postgrex.Query, Postgrex.Stream, Time, URI, Version, Version.Requirement
            (elixir) /private/tmp/elixir-20170801-32483-1rf8an1/elixir-1.5.1/lib/elixir/lib/string/chars.ex:3: String.Chars.impl_for!/1
            (elixir) /private/tmp/elixir-20170801-32483-1rf8an1/elixir-1.5.1/lib/elixir/lib/string/chars.ex:22: String.Chars.to_string/1
            (drab) lib/drab/live/cache.ex:60: Drab.Live.Cache.cache_file/0
            (drab) lib/drab/live/cache.ex:24: Drab.Live.Cache.start/0
            (drab) lib/drab/supervisor.ex:26: Drab.Supervisor.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
```

The problem appears to be coming from https://github.com/grych/drab/blob/master/lib/drab/live/cache.ex#L60, where the call to `Drab.Config.app_name()` returns nil I believe, and then when it is piped into `:code.priv_dir` it results in a `{:error, :bad_name}` tuple being returned.

**Comment by justincjohnson** [comment]
Ah, I see if I add this config I get around the problem.

```
config :drab,
  main_phoenix_app: :app_web
```

**Comment by grych** [comment]
Thanks for reporting. This is a next issue with how Drab finds your application name.

**Comment by grych** [comment]
Your workaround is actually a solution: under umbrella, you must specify your app name in the `config.exs`. I've updated the installation docs, as well as showing better error in this case.

**Comment by justincjohnson** [comment]
I thought that might be the case.  Doc update sounds great.  Thanks!
