### ISSUE TITLE
no match of right hand side value: {:error, "timed out after 5000 ms."} 

### ISSUE THREAD

**Issue by JanStevens** [grych/drab#68]
We see this on production from time to time when somebody is surfing around and we try to establish a socket connection. Using latest firefox, on OTP 20.1 / Elixir 1.5.1

```
17:02:57.903 request_id=e35t5rdo07660flfisqr1a3or10om26n [info] GET /
17:02:57.909 request_id=e35t5rdo07660flfisqr1a3or10om26n [info] Sent 200 in 6ms
17:02:58.217 [info] JOIN "__drab:topic:shared" to Drab.Channel
  Transport:  Phoenix.Transports.WebSocket (2.0.0)
  Serializer:  Phoenix.Transports.V2.WebSocketSerializer
  Parameters: %{}
17:02:58.217 [info] Replied __drab:topic:shared :ok
17:03:02.248 [error] GenServer #PID<0.2221.0> terminating
** (MatchError) no match of right hand side value: {:error, "timed out after 5000 ms."}
    (drab) lib/drab/core.ex:418: Drab.Core.session/1
    (drab) lib/drab.ex:154: Drab.handle_cast/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:onconnect, %Phoenix.Socket{assigns: %{__action: :index, __broadcast_topic: "topic:shared", __controller: LocalScanningWeb.IdentifierController, __drab_pid: #PID<0.2221.0>}, channel: Drab.Channel, channel_pid: #PID<0.2220.0>, endpoint: LocalScanningWeb.Endpoint, handler: LocalScanningWeb.UserSocket, id: nil, join_ref: "1", joined: true, private: %{log_handle_in: :debug, log_join: :info}, pubsub_server: LocalScanning.PubSub, ref: "2", serializer: Phoenix.Transports.V2.WebSocketSerializer, topic: "__drab:topic:shared", transport: Phoenix.Transports.WebSocket, transport_name: :websocket, transport_pid: #PID<0.2219.0>, vsn: "2.0.0"}, %{}}}

=CRASH REPORT==== 7-Dec-2017::17:03:02 ===
  crasher:
    initial call: Elixir.Drab:init/1
    pid: <0.2221.0>
    registered_name: []
    exception exit: {{badmatch,{error,<<"timed out after 5000 ms.">>}},
                     [{'Elixir.Drab.Core',session,1,
                          [{file,"lib/drab/core.ex"},{line,418}]},
                      {'Elixir.Drab',handle_cast,2,
                          [{file,"lib/drab.ex"},{line,154}]},
                      {gen_server,try_dispatch,4,
                          [{file,"gen_server.erl"},{line,601}]},
                      {gen_server,handle_msg,5,
                          [{file,"gen_server.erl"},{line,667}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,247}]}]}
      in function  gen_server:terminate/7 (gen_server.erl, line 812)
    ancestors: [<0.2220.0>,<0.2219.0>]
    messages: [{'$gen_cast',
                      {onload,
                          #{'__struct__' => 'Elixir.Phoenix.Socket',
                            assigns =>
                                #{'__action' => index,
                                  '__broadcast_topic' => <<"topic:shared">>,
                                  '__controller' =>
                                      'Elixir.LocalScanningWeb.IdentifierController',
                                  '__drab_pid' => <0.2221.0>},
                            channel => 'Elixir.Drab.Channel',
                            channel_pid => <0.2220.0>,
                            endpoint => 'Elixir.LocalScanningWeb.Endpoint',
                            handler => 'Elixir.LocalScanningWeb.UserSocket',
                            id => nil,join_ref => <<"1">>,joined => true,
                            private =>
                                #{log_handle_in => debug,log_join => info},
                            pubsub_server => 'Elixir.LocalScanning.PubSub',
                            ref => <<"3">>,
                            serializer =>
                                'Elixir.Phoenix.Transports.V2.WebSocketSerializer',
                            topic => <<"__drab:topic:shared">>,
                            transport => 'Elixir.Phoenix.Transports.WebSocket',
                            transport_name => websocket,
                            transport_pid => <0.2219.0>,vsn => <<"2.0.0">>}}},
                  {'EXIT',<0.2220.0>,{shutdown,closed}}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 822
  neighbours:
```

**Comment by grych** [comment]
It is not easy to debug, as it happens from time to time, but I've fixed the way how Drab is getting the store and session tokens; hope it will do the trick
