### ISSUE TITLE
Evaluating expression nested in a block

### ISSUE THREAD

**Issue by ashwanip** [grych/drab#74]
Code similar for following causes an error on change of value for **@cities_list**

**CODE**
```
    <%= if @selected_province && @selected_province.id && Enum.count(@cities_list) > 0 do %>
           <%= 
                   Enum.map(@cities_list, fn(city) -> 
                            Phoenix.View.render(SharangaAdminWeb.LocationManagement.CityView, 
                                            "city_list_item.html", 
                                            province: @selected_province, 
                                            country: @selected_country,
                                            city: city,
                                            conn: @conn)
                                end
                   ) 
              %>
     <% end %>
```

**ERROR**
```
[error] Drab Handler failed with the following exception:
** (MatchError) no match of right hand side value: {:error, "Cannot read property 'querySelectorAll' of null"}
    (drab) lib/drab/live.ex:395: Drab.Live.do_poke/5
    (drab) lib/drab.ex:257: anonymous fn/6 in Drab.handle_event/6
```

Potential reason for the error is having  an expression inside the block. It might be helpful in certain other situations, to allow expressions nested in the block to be evaluated properly. Although the above code could have been written as following to fix the error (_thanks @grych_)
```
    <%= if @selected_province && @selected_province.id && Enum.count(@cities_list) > 0 do
                  Enum.map(@cities_list, fn(city) -> 
                        Phoenix.View.render(SharangaAdminWeb.LocationManagement.CityView, 
                                            "city_list_item.html", 
                                            province: @selected_province, 
                                            country: @selected_country,
                                            city: city,
                                            conn: @conn)
                                end
                    ) 
      end %>
```

**Comment by grych** [comment]
Fixed with 12fb8cc135d5958d11da2d4e933e4c853bb75225.
Proven to work with the equivalent code:

<%= if @user && Enum.count(@users) > 0 do %>
  <%=
    Enum.map(@users, fn u ->
      render("user.html", user: u, conn: @conn)
    end)
  %>
<% end %>
